### ISSUE TITLE
"Regroup similar results" option doesn't work.

### ISSUE THREAD

**Issue by poikende** [exile-center/better-trading#113]
Before, same items from the same seller would get grouped together and there would be a button "21 similar results" or something in that fashion. So I would know that the person has 22 items. 
Since at least half a year, this option has been gone for me. I don't seem to have any other PoE extensions installed.

What happens instead is I only see 1 item from the seller and the other ones from that seller just disappear. No "# similar results" button, basically.

Option off - https://i.imgur.com/XZJ0tfq.png, option on - https://i.imgur.com/le6mXMX.png
The same is true in default view.

**Comment by pboutin** [comment]
The feature was removed since the trade site itself implemented something similar that conflicted with the extension.

**Comment by dbjorge** [comment]
Hi @poikende,

Thanks for reporting the issue! I was able to confirm the behavior you described. I've implemented a fix in https://github.com/exile-center/better-trading/commit/b02066689eeb0e8fa66f26b44a0185e2dfc06f5e - it will be included in the next release.

Like @pboutin mentioned, this functionality is a little redundant with the similar regroup results feature the trade site provides by default, but I think the version the extension provides is a little nicer (now that it's fixed) in that it lets you collapse and uncollapse the results instead of just omitting them, so I've fixed the old functionality rather than removing it in favor of the built-in version.

Also like @pboutin mentioned, the fix to make the feature work generally does not help with the specific issue that beasts are considered "different" by the trade site (and thus, the extension) when they have different names/modifiers/etc - I verified the fix in the above commit against your "enlighten 3" example, but it doesn't help with beasts specifically. If you'd like to see beast grouping specifically, please file a separate issue for that with more details of the exact criteria you'd like to see for considering beasts to be "similar" for grouping purposes (beast type + ilvl?)

**Comment by dbjorge** [comment]
Fix released in 1.7.1. Closing this issue accordingly, but like I mentioned above, feel free to open a separate feature request issue if you'd like to track the beast grouping stuff specifically.
