### ISSUE TITLE
[Request] Save the URL Query instead of just the search ID

### ISSUE THREAD

**Issue by Srlimao** [exile-center/better-trading#131]
Is it possible to save the search URL with the query instead of just the search ID? so its not league dependent
[Like this](https://www.pathofexile.com/trade/search/Crucible?q={%22query%22:{%22stats%22:[{%22type%22:%22and%22,%22filters%22:[{%22id%22:%22pseudo.pseudo_total_elemental_resistance%22,%22value%22:{%22min%22:45},%22disabled%22:false},{%22id%22:%22pseudo.pseudo_number_of_suffix_mods%22,%22value%22:{%22max%22:2},%22disabled%22:false}],%22disabled%22:false}],%22status%22:{%22option%22:%22online%22},%22filters%22:{%22misc_filters%22:{%22filters%22:{%22crafted%22:{%22option%22:%22false%22},%22mirrored%22:{%22option%22:%22false%22},%22corrupted%22:{%22option%22:%22false%22}},%22disabled%22:false},%22type_filters%22:{%22filters%22:{%22rarity%22:{%22option%22:%22rare%22},%22category%22:{%22option%22:%22accessory.ring%22}},%22disabled%22:false},%22trade_filters%22:{%22filters%22:{%22price%22:{%22max%22:16794,%22min%22:16794}},%22disabled%22:false}}}})
Instead of [this](https://www.pathofexile.com/trade/search/Standard/jB4LvpkuX)

**Comment by pboutin** [comment]
The search ID is not league dependent. If you change the "active" league on the trade site, the bookmarks will start pointing on the active league. (Maybe it changed but since we're in between leagues I can validate for sure)

**Comment by Srlimao** [comment]
Hm some of my old searches become invalid if I don't use it for some time, I thought saving the query URL it could solve that

**Comment by dbjorge** [comment]
That's a separate issue; the trade website periodically cleans out old unused search queries on its end. A search that you haven't visited in a long time will become unavailable on the website regardless of whether you save it using the extension or a regular browser bookmark.

**Comment by Srlimao** [comment]
Understood, and is possible to save the query URL in better trading? I made a small extension to extract that and save in my bookmarks

**Comment by dbjorge** [comment]
Looking at this again I now see that I misunderstood the original question. What you're asking is whether, rather than storing the query ID pulled out of the trade site url (like `QrVX393tw`) and having bookmarks navigate to URLs like `https://www.pathofexile.com/trade/search/Ancestor/QrVX393tw`, we can instead query the internal trade site API on bookmark update (`https://www.pathofexile.com/api/trade/search/Ancestor/QrVX393tw`) and store the result such that bookmarks navigate to URLs like `https://www.pathofexile.com/trade/search/Ancestor?q={"query": { /* JSON description of selected filters */}}`.

I agree that you could technically use something like that to enable bookmarks that don't become stale when the original trade queries expire, but we're not going to implement it in Better Trading because it would require making requests to internal website API endpoints (the internal API to grab the query JSON and also the undocumented `q=` form of the trade site URL), which is expressly forbidden by the Path of Exile developer docs and terms of use.
