### ISSUE TITLE
Updating URL's Between Leagues

### ISSUE THREAD

**Issue by dgideon** [exile-center/better-trading#142]
Love this plugin. It has seriously become a cornerstone to my PoE experience. Thank you!

My question is there any process by which we can recover URL's that have been saved for item searches that are no longer valid?

For instance, you've saved a weapon search with all the desired filters for 1 league and then 1 or 2 leagues later it no longer works. This would be especially helpful for those of us who tend to revive a build again and again each league and try to push it to new heights.

Even if there was a way we could "copy" the old parameters to import to the new league and update the URL, that would be awesome.

Or, do you have any tips or suggestions for me that I might be missing?

**Comment by dbjorge** [comment]
Unfortunately, this isn't functionality that we could provide while still staying in bounds of PoE's developer terms of service (see https://github.com/exile-center/better-trading/issues/131#issuecomment-1722568041 for past discussion on this). The way search URLs expire is part of the default trade site, not something the extension is responsible for.

As far as workarounds go, I think the easiest option you could take right now would be to open the searches every now and then; I'm not sure exactly how long it takes for them to expire, but my recollection is that it's on the order of 30-60 days.

**Comment by mfarrugi** [comment]
This would also fix some spurious `Failed to load search state. The search is no longer valid.` errors, that I think happen because the trade site doesn't always (immediately? globally?) cache queries.

I think that if poe.ninja, pob, and many others link to the trade site with urls like [this](https://www.pathofexile.com/trade/search/Mercenaries?q=%7B%22query%22%3A%7B%22filters%22%3A%7B%22type_filters%22%3A%7B%22filters%22%3A%7B%7D%7D%7D%2C%22name%22%3A%22Goldrim%22%7D%7D), we shouldn't be concerned with doing that here as well. @dbjorge are you specifically concerned with getting the json query from https://www.pathofexile.com/api/trade/search/Standard/nrblf0?
