### ISSUE TITLE
Disabling extension deletes saved searches

### ISSUE THREAD

**Issue by Mar-vo** [exile-center/better-trading#39]
I have recently disabled this extenstion to find what was highjacking my search.
And... all of my saved searches are now gone. Very sad :(
If these could be saved in a more permanent folder (and exportable) that would be very appreciated.

**Comment by pboutin** [comment]
This will be completely addressed in the upcoming release in 2 ways:

The bookmarks data will now be persisted in the browser's extension storage instead of the trade site localStorage, which should be more reliable. (uninstalling the extension might wipe its data thought 🤔 )

But, the export/import feature for bookmark folders will also be there.

The next version should be out a few days before the next league, on both Chrome and Firefox :)

**Comment by pboutin** [comment]
Little sneak peak 😉 
![image](https://user-images.githubusercontent.com/4255460/82108260-4d88f380-96fb-11ea-9340-f6a1a4c7f34b.png)
