### ISSUE TITLE
Any way to retain searches if "cleaning" PC?

### ISSUE THREAD

**Issue by cjhowell** [exile-center/better-trading#40]
Didn't think about it properly early and went ahead with the nag I'd had for several days from CCleaner to save 1+GB of data.

Obviously I can choose not to include browser cookies but is there any option to save/backup saved searches so they are not wiped if I forget the CCleaner setting in the future?

Would also be handy to have an option to backup/export saved searches to be able to have them saved outside the browser and to easily transfer saved searches between computers. For myself, I do a fair bit of trade searching on my laptop and have stuff saved their. Game is played on PC so I have to recreate the searches on PC for now my emailing each search URL and saving them to PC (where I just wiped everything)

**Comment by pboutin** [comment]
This will be completely addressed in the upcoming release in 2 ways:

The bookmarks data will now be persisted in the browser's extension storage instead of the trade site localStorage, which should be more reliable.

Also, the export/import feature for bookmark folders will also be there.

The next version should be out a few days before the next league, on both Chrome and Firefox :)

**Comment by pboutin** [comment]
Little sneak peak 😉 
![image](https://user-images.githubusercontent.com/4255460/82108260-4d88f380-96fb-11ea-9340-f6a1a4c7f34b.png)
