### ISSUE TITLE
Sort by quantity.

### ISSUE THREAD

**Issue by VayashMoru** [exile-center/better-trading#80]
With the recent death of poeapp.com we are severely lacking in ways to find items in large quantities that are not included in the Bulk section, such as prophecies. The extention already notifies us if the seller has many units of a given item. Would it be possible to sort the search by most units?

**Comment by pboutin** [comment]
That would not be possible since the ordering is done server-side, and the extension can only change what's loaded locally.

That being said, you can search for minimum stock, found it useful when I want to buy in bulk:
![image](https://user-images.githubusercontent.com/4255460/111166168-39f62580-8576-11eb-8bc5-20fa210ed239.png)
